sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bwooldridge55/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bwooldridge55/docker-react npm run test